//
//  DashboardRouter.swift
//  SnakeJazz
//
//  Created by Lluís Morató on 6/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DashboardRoutingLogic {
    func goToCharactersList()
    func goToEpisodesList()
    func goToLocationsList()
}

protocol DashboardDataPassing {
    var dataStore: DashboardDataStore? { get }
}

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing {
    weak var viewController: DashboardViewController?
    var dataStore: DashboardDataStore?
    
    func goToCharactersList() {
        let charactersListViewController = CharactersViewController(nibName: CharactersViewController.nibName(), bundle: nil)
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(charactersListViewController, animated: true)
        } else {
            viewController?.present(charactersListViewController, animated: true)
        }
    }
    
    func goToEpisodesList() {
        let episodesListViewController = EpisodesViewController(nibName: EpisodesViewController.nibName(), bundle: nil)
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(episodesListViewController, animated: true)
        } else {
            viewController?.present(episodesListViewController, animated: true)
        }
    }
    
    func goToLocationsList() {
        let locationsListViewController = LocationsViewController(nibName: LocationsViewController.nibName(), bundle: nil)
        if let navigationController = viewController?.navigationController {
            navigationController.pushViewController(locationsListViewController, animated: true)
        } else {
            viewController?.present(locationsListViewController, animated: true)
        }
    }
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: DashboardViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: DashboardDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
