//
//  DashboardPresenter.swift
//  SnakeJazz
//
//  Created by Lluís Morató on 6/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic {
    //  func presentSomething(response: Dashboard.Something.Response)
}

class DashboardPresenter: DashboardPresentationLogic {
    weak var viewController: DashboardDisplayLogic?
}
