//
//  CharactersModels.swift
//  SnakeJazz
//
//  Created by Lluís Morató on 6/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct CharactersViewModel {
    struct Character {
        let id: Int
        let name: String
        let status: CharactersViewModel.CharacterStatus
        let type: String
        let gender: CharactersViewModel.CharacterGender
        let origin: String
        let lastLocation: String
        let image: String
    }
    
    enum CharacterStatus: CaseIterable {
        case dead
        case alive
        case unknown
        
        func getDisplayName() -> String {
            switch self {
            case .dead:
                String(localized: "characters_status_dead")
            case .alive:
                String(localized: "characters_status_alive")
            case .unknown:
                String(localized: "characters_status_unknown")
            }
        }
    }
    
    enum CharacterGender: CaseIterable {
        case male
        case female
        case genderless
        case unknown
        
        func getDisplayName() -> String {
            switch self {
            case .male:
                String(localized: "characters_gender_male")
            case .female:
                String(localized: "characters_gender_female")
            case .genderless:
                String(localized: "characters_gender_genderless")
            case .unknown:
                String(localized: "characters_gender_unknown")
            }
        }
    }
    
    struct PaginationInformation {
        let charactersTotal: Int
        let numberOfPages: Int
        let currentPage: Int
    }
}
