# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnakeJazz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnakeJazz
  pod 'Kingfisher', '~> 7.0'

  target 'SnakeJazzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnakeJazzUITests' do
    # Pods for testing
  end

end
