//
//  CharactersGridRouter.swift
//  SnakeJazz
//
//  Created by Lluís Morató on 9/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharactersGridRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CharactersGridDataPassing {
    var dataStore: CharactersGridDataStore? { get }
}

class CharactersGridRouter: NSObject, CharactersGridRoutingLogic, CharactersGridDataPassing {
    weak var viewController: CharactersGridViewController?
    var dataStore: CharactersGridDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: CharactersGridViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: CharactersGridDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
